#!/usr/bin/env bash

# Install Homebrew
if test ! "$(command -v brew)"; then
  echo "Homebrew is not installed!"
  exit 1
fi

# Install brew apps
brew bundle

if [[ -e ~/.Brewfile ]]; then
  brew bundle --file=~/.Brewfile
fi

# Install oh-my-zsh
if [[ ! -f ~/.antigen.zsh ]]; then
  curl -s -L git.io/antigen > ~/.antigen.zsh
fi

if [[ ! -d ~/.oh-my-zsh/ ]]; then
  echo "* Installing oh-my-zsh"
  git clone --quiet https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh > /dev/null
  ZSH_PATH=$(command -v zsh)
  if ! grep -q "$ZSH_PATH" '/etc/shells'; then
    echo "$ZSH_PATH" | sudo tee -a /etc/shells
  fi
  chsh -s "$ZSH_PATH"
fi

